version: "3"
services:
  mysql:
    image: mysql
    container_name: test-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: my
      MYSQL_PASSWORD: mypass
      MYSQL_DATABASE: mydb
    volumes:
      - ./data:/var/lib/mysql
